### ISSUE TITLE
IMPORTANTE: Adicionar metadado ao criar entidades indicando site de origem

### ISSUE THREAD

**Issue by leogermani** [culturagovbr/mapasculturais-baseminc#5]
Sempre ao criar uma nova entidade, criar um metadado que indique o site por meio do qual ela foi criado.

exemplo: site_origem = redevc
site_origem = museus

**Comment by rafaelchavesfreitas** [comment]
vou criar um plugin que adiciona o metadado *_origem* e usa um valor configurado

**Comment by marylly** [comment]
Necessário alterar o nome do metadado de "site" para outro nome como "site_origem". Existem outros metadados nas entidades que já usa o nome "site".

**Comment by marylly** [comment]
Poderiam validar este Plugin @GustavoVS, por gentileza.

**Comment by thaisrigolon** [comment]
Ok, issue homologada.
